services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5436:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/init_database:/docker-entrypoint-initdb.d

  app:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "18080:18080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - app

volumes:
  pgdata:
